// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hp.proto

package hp

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Enums
type Language int32

const (
	Language_HINDI    Language = 0
	Language_ENGLISH  Language = 1
	Language_GARHWALI Language = 2
)

var Language_name = map[int32]string{
	0: "HINDI",
	1: "ENGLISH",
	2: "GARHWALI",
}

var Language_value = map[string]int32{
	"HINDI":    0,
	"ENGLISH":  1,
	"GARHWALI": 2,
}

func (x Language) String() string {
	return proto.EnumName(Language_name, int32(x))
}

func (Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{0}
}

type Role int32

const (
	Role_ADMIN_ROLE         Role = 0
	Role_POST_APPROVAL_ROLE Role = 1
	Role_USER_ROLE          Role = 2
)

var Role_name = map[int32]string{
	0: "ADMIN_ROLE",
	1: "POST_APPROVAL_ROLE",
	2: "USER_ROLE",
}

var Role_value = map[string]int32{
	"ADMIN_ROLE":         0,
	"POST_APPROVAL_ROLE": 1,
	"USER_ROLE":          2,
}

func (x Role) String() string {
	return proto.EnumName(Role_name, int32(x))
}

func (Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{1}
}

type ParentType int32

const (
	ParentType_POST    ParentType = 0
	ParentType_COMMENT ParentType = 1
)

var ParentType_name = map[int32]string{
	0: "POST",
	1: "COMMENT",
}

var ParentType_value = map[string]int32{
	"POST":    0,
	"COMMENT": 1,
}

func (x ParentType) String() string {
	return proto.EnumName(ParentType_name, int32(x))
}

func (ParentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{2}
}

type Field int32

const (
	Field_ID     Field = 0
	Field_MOBILE Field = 1
	Field_EMAIL  Field = 2
)

var Field_name = map[int32]string{
	0: "ID",
	1: "MOBILE",
	2: "EMAIL",
}

var Field_value = map[string]int32{
	"ID":     0,
	"MOBILE": 1,
	"EMAIL":  2,
}

func (x Field) String() string {
	return proto.EnumName(Field_name, int32(x))
}

func (Field) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{3}
}

type Category int32

const (
	Category_SPORTS        Category = 0
	Category_NEWS          Category = 1
	Category_LIFESTYLE     Category = 2
	Category_INFOTAINMENT  Category = 3
	Category_ENTERTAINMENT Category = 4
	Category_TECHNOLOGY    Category = 5
	Category_SPIRITUAL     Category = 6
)

var Category_name = map[int32]string{
	0: "SPORTS",
	1: "NEWS",
	2: "LIFESTYLE",
	3: "INFOTAINMENT",
	4: "ENTERTAINMENT",
	5: "TECHNOLOGY",
	6: "SPIRITUAL",
}

var Category_value = map[string]int32{
	"SPORTS":        0,
	"NEWS":          1,
	"LIFESTYLE":     2,
	"INFOTAINMENT":  3,
	"ENTERTAINMENT": 4,
	"TECHNOLOGY":    5,
	"SPIRITUAL":     6,
}

func (x Category) String() string {
	return proto.EnumName(Category_name, int32(x))
}

func (Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{4}
}

type Post_Type int32

const (
	Post_TEXT  Post_Type = 0
	Post_IMAGE Post_Type = 1
	Post_VIDEO Post_Type = 2
)

var Post_Type_name = map[int32]string{
	0: "TEXT",
	1: "IMAGE",
	2: "VIDEO",
}

var Post_Type_value = map[string]int32{
	"TEXT":  0,
	"IMAGE": 1,
	"VIDEO": 2,
}

func (x Post_Type) String() string {
	return proto.EnumName(Post_Type_name, int32(x))
}

func (Post_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{2, 0}
}

type UserProfile_Gender int32

const (
	UserProfile_MALE              UserProfile_Gender = 0
	UserProfile_FEMALE            UserProfile_Gender = 1
	UserProfile_PREFER_NOT_TO_SAY UserProfile_Gender = 3
)

var UserProfile_Gender_name = map[int32]string{
	0: "MALE",
	1: "FEMALE",
	3: "PREFER_NOT_TO_SAY",
}

var UserProfile_Gender_value = map[string]int32{
	"MALE":              0,
	"FEMALE":            1,
	"PREFER_NOT_TO_SAY": 3,
}

func (x UserProfile_Gender) String() string {
	return proto.EnumName(UserProfile_Gender_name, int32(x))
}

func (UserProfile_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{5, 0}
}

// Objects
type Feed struct {
	Likes                []string   `protobuf:"bytes,1,rep,name=likes,proto3" json:"likes,omitempty"`
	Comments             []*Comment `protobuf:"bytes,2,rep,name=comments,proto3" json:"comments,omitempty"`
	TotalLikes           int64      `protobuf:"varint,3,opt,name=total_likes,json=totalLikes,proto3" json:"total_likes,omitempty"`
	TotalComments        int64      `protobuf:"varint,4,opt,name=total_comments,json=totalComments,proto3" json:"total_comments,omitempty"`
	Post                 *Post      `protobuf:"bytes,5,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Feed) Reset()         { *m = Feed{} }
func (m *Feed) String() string { return proto.CompactTextString(m) }
func (*Feed) ProtoMessage()    {}
func (*Feed) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{0}
}

func (m *Feed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feed.Unmarshal(m, b)
}
func (m *Feed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feed.Marshal(b, m, deterministic)
}
func (m *Feed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feed.Merge(m, src)
}
func (m *Feed) XXX_Size() int {
	return xxx_messageInfo_Feed.Size(m)
}
func (m *Feed) XXX_DiscardUnknown() {
	xxx_messageInfo_Feed.DiscardUnknown(m)
}

var xxx_messageInfo_Feed proto.InternalMessageInfo

func (m *Feed) GetLikes() []string {
	if m != nil {
		return m.Likes
	}
	return nil
}

func (m *Feed) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *Feed) GetTotalLikes() int64 {
	if m != nil {
		return m.TotalLikes
	}
	return 0
}

func (m *Feed) GetTotalComments() int64 {
	if m != nil {
		return m.TotalComments
	}
	return 0
}

func (m *Feed) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type UserCategory struct {
	UserId               string     `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Categories           []Category `protobuf:"varint,3,rep,packed,name=categories,proto3,enum=Category" json:"categories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UserCategory) Reset()         { *m = UserCategory{} }
func (m *UserCategory) String() string { return proto.CompactTextString(m) }
func (*UserCategory) ProtoMessage()    {}
func (*UserCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{1}
}

func (m *UserCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCategory.Unmarshal(m, b)
}
func (m *UserCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCategory.Marshal(b, m, deterministic)
}
func (m *UserCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCategory.Merge(m, src)
}
func (m *UserCategory) XXX_Size() int {
	return xxx_messageInfo_UserCategory.Size(m)
}
func (m *UserCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCategory.DiscardUnknown(m)
}

var xxx_messageInfo_UserCategory proto.InternalMessageInfo

func (m *UserCategory) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserCategory) GetCategories() []Category {
	if m != nil {
		return m.Categories
	}
	return nil
}

type Post struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt            int64             `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	PostType             Post_Type         `protobuf:"varint,3,opt,name=post_type,json=postType,proto3,enum=Post_Type" json:"post_type,omitempty"`
	Category             Category          `protobuf:"varint,4,opt,name=category,proto3,enum=Category" json:"category,omitempty"`
	CreatorId            string            `protobuf:"bytes,5,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	Heading              string            `protobuf:"bytes,6,opt,name=heading,proto3" json:"heading,omitempty"`
	Body                 string            `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	ResourceUrls         map[string]string `protobuf:"bytes,8,rep,name=resource_urls,json=resourceUrls,proto3" json:"resource_urls,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Labels               map[string]string `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{2}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Post) GetPostType() Post_Type {
	if m != nil {
		return m.PostType
	}
	return Post_TEXT
}

func (m *Post) GetCategory() Category {
	if m != nil {
		return m.Category
	}
	return Category_SPORTS
}

func (m *Post) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *Post) GetHeading() string {
	if m != nil {
		return m.Heading
	}
	return ""
}

func (m *Post) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Post) GetResourceUrls() map[string]string {
	if m != nil {
		return m.ResourceUrls
	}
	return nil
}

func (m *Post) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type Like struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId             string   `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	CreatorId            string   `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Like) Reset()         { *m = Like{} }
func (m *Like) String() string { return proto.CompactTextString(m) }
func (*Like) ProtoMessage()    {}
func (*Like) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{3}
}

func (m *Like) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Like.Unmarshal(m, b)
}
func (m *Like) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Like.Marshal(b, m, deterministic)
}
func (m *Like) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Like.Merge(m, src)
}
func (m *Like) XXX_Size() int {
	return xxx_messageInfo_Like.Size(m)
}
func (m *Like) XXX_DiscardUnknown() {
	xxx_messageInfo_Like.DiscardUnknown(m)
}

var xxx_messageInfo_Like proto.InternalMessageInfo

func (m *Like) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Like) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *Like) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

type Comment struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatorId            string   `protobuf:"bytes,3,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ParentId             string   `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Body                 string   `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Comment) Reset()         { *m = Comment{} }
func (m *Comment) String() string { return proto.CompactTextString(m) }
func (*Comment) ProtoMessage()    {}
func (*Comment) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{4}
}

func (m *Comment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Comment.Unmarshal(m, b)
}
func (m *Comment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Comment.Marshal(b, m, deterministic)
}
func (m *Comment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Comment.Merge(m, src)
}
func (m *Comment) XXX_Size() int {
	return xxx_messageInfo_Comment.Size(m)
}
func (m *Comment) XXX_DiscardUnknown() {
	xxx_messageInfo_Comment.DiscardUnknown(m)
}

var xxx_messageInfo_Comment proto.InternalMessageInfo

func (m *Comment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Comment) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Comment) GetCreatorId() string {
	if m != nil {
		return m.CreatorId
	}
	return ""
}

func (m *Comment) GetParentId() string {
	if m != nil {
		return m.ParentId
	}
	return ""
}

func (m *Comment) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type UserProfile struct {
	Id                   string             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsActive             bool               `protobuf:"varint,2,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsCompleted          bool               `protobuf:"varint,3,opt,name=is_completed,json=isCompleted,proto3" json:"is_completed,omitempty"`
	CreateTime           int64              `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           int64              `protobuf:"varint,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	FirstName            string             `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string             `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Gender               UserProfile_Gender `protobuf:"varint,8,opt,name=gender,proto3,enum=UserProfile_Gender" json:"gender,omitempty"`
	Language             Language           `protobuf:"varint,9,opt,name=language,proto3,enum=Language" json:"language,omitempty"`
	Mobile               string             `protobuf:"bytes,10,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Email                string             `protobuf:"bytes,11,opt,name=email,proto3" json:"email,omitempty"`
	Username             string             `protobuf:"bytes,12,opt,name=username,proto3" json:"username,omitempty"`
	Password             string             `protobuf:"bytes,13,opt,name=password,proto3" json:"password,omitempty"`
	Address              string             `protobuf:"bytes,14,opt,name=address,proto3" json:"address,omitempty"`
	Role                 Role               `protobuf:"varint,15,opt,name=role,proto3,enum=Role" json:"role,omitempty"`
	DisplayPictureUrl    string             `protobuf:"bytes,16,opt,name=display_picture_url,json=displayPictureUrl,proto3" json:"display_picture_url,omitempty"`
	Labels               map[string]string  `protobuf:"bytes,17,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{5}
}

func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfile.Unmarshal(m, b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
}
func (m *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(m, src)
}
func (m *UserProfile) XXX_Size() int {
	return xxx_messageInfo_UserProfile.Size(m)
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserProfile) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *UserProfile) GetIsCompleted() bool {
	if m != nil {
		return m.IsCompleted
	}
	return false
}

func (m *UserProfile) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *UserProfile) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *UserProfile) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserProfile) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserProfile) GetGender() UserProfile_Gender {
	if m != nil {
		return m.Gender
	}
	return UserProfile_MALE
}

func (m *UserProfile) GetLanguage() Language {
	if m != nil {
		return m.Language
	}
	return Language_HINDI
}

func (m *UserProfile) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *UserProfile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserProfile) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserProfile) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserProfile) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *UserProfile) GetRole() Role {
	if m != nil {
		return m.Role
	}
	return Role_ADMIN_ROLE
}

func (m *UserProfile) GetDisplayPictureUrl() string {
	if m != nil {
		return m.DisplayPictureUrl
	}
	return ""
}

func (m *UserProfile) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type GetAllPostRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllPostRequest) Reset()         { *m = GetAllPostRequest{} }
func (m *GetAllPostRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllPostRequest) ProtoMessage()    {}
func (*GetAllPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{6}
}

func (m *GetAllPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPostRequest.Unmarshal(m, b)
}
func (m *GetAllPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPostRequest.Marshal(b, m, deterministic)
}
func (m *GetAllPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPostRequest.Merge(m, src)
}
func (m *GetAllPostRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllPostRequest.Size(m)
}
func (m *GetAllPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPostRequest proto.InternalMessageInfo

func (m *GetAllPostRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetAllPostResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Posts                []*Post  `protobuf:"bytes,2,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllPostResponse) Reset()         { *m = GetAllPostResponse{} }
func (m *GetAllPostResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllPostResponse) ProtoMessage()    {}
func (*GetAllPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{7}
}

func (m *GetAllPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllPostResponse.Unmarshal(m, b)
}
func (m *GetAllPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllPostResponse.Marshal(b, m, deterministic)
}
func (m *GetAllPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllPostResponse.Merge(m, src)
}
func (m *GetAllPostResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllPostResponse.Size(m)
}
func (m *GetAllPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllPostResponse proto.InternalMessageInfo

func (m *GetAllPostResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetAllPostResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type CommentRequest struct {
	Comment              *Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentRequest) Reset()         { *m = CommentRequest{} }
func (m *CommentRequest) String() string { return proto.CompactTextString(m) }
func (*CommentRequest) ProtoMessage()    {}
func (*CommentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{8}
}

func (m *CommentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentRequest.Unmarshal(m, b)
}
func (m *CommentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentRequest.Marshal(b, m, deterministic)
}
func (m *CommentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentRequest.Merge(m, src)
}
func (m *CommentRequest) XXX_Size() int {
	return xxx_messageInfo_CommentRequest.Size(m)
}
func (m *CommentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommentRequest proto.InternalMessageInfo

func (m *CommentRequest) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

type CommentResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Comment              *Comment `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommentResponse) Reset()         { *m = CommentResponse{} }
func (m *CommentResponse) String() string { return proto.CompactTextString(m) }
func (*CommentResponse) ProtoMessage()    {}
func (*CommentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{9}
}

func (m *CommentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommentResponse.Unmarshal(m, b)
}
func (m *CommentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommentResponse.Marshal(b, m, deterministic)
}
func (m *CommentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommentResponse.Merge(m, src)
}
func (m *CommentResponse) XXX_Size() int {
	return xxx_messageInfo_CommentResponse.Size(m)
}
func (m *CommentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CommentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CommentResponse proto.InternalMessageInfo

func (m *CommentResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CommentResponse) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

type LikeRequest struct {
	Like                 *Like    `protobuf:"bytes,1,opt,name=like,proto3" json:"like,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeRequest) Reset()         { *m = LikeRequest{} }
func (m *LikeRequest) String() string { return proto.CompactTextString(m) }
func (*LikeRequest) ProtoMessage()    {}
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{10}
}

func (m *LikeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeRequest.Unmarshal(m, b)
}
func (m *LikeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeRequest.Marshal(b, m, deterministic)
}
func (m *LikeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeRequest.Merge(m, src)
}
func (m *LikeRequest) XXX_Size() int {
	return xxx_messageInfo_LikeRequest.Size(m)
}
func (m *LikeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LikeRequest proto.InternalMessageInfo

func (m *LikeRequest) GetLike() *Like {
	if m != nil {
		return m.Like
	}
	return nil
}

type LikeResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Like                 *Like    `protobuf:"bytes,2,opt,name=like,proto3" json:"like,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LikeResponse) Reset()         { *m = LikeResponse{} }
func (m *LikeResponse) String() string { return proto.CompactTextString(m) }
func (*LikeResponse) ProtoMessage()    {}
func (*LikeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{11}
}

func (m *LikeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LikeResponse.Unmarshal(m, b)
}
func (m *LikeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LikeResponse.Marshal(b, m, deterministic)
}
func (m *LikeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LikeResponse.Merge(m, src)
}
func (m *LikeResponse) XXX_Size() int {
	return xxx_messageInfo_LikeResponse.Size(m)
}
func (m *LikeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LikeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LikeResponse proto.InternalMessageInfo

func (m *LikeResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LikeResponse) GetLike() *Like {
	if m != nil {
		return m.Like
	}
	return nil
}

type PostRequest struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostRequest) Reset()         { *m = PostRequest{} }
func (m *PostRequest) String() string { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()    {}
func (*PostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{12}
}

func (m *PostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRequest.Unmarshal(m, b)
}
func (m *PostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRequest.Marshal(b, m, deterministic)
}
func (m *PostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRequest.Merge(m, src)
}
func (m *PostRequest) XXX_Size() int {
	return xxx_messageInfo_PostRequest.Size(m)
}
func (m *PostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostRequest proto.InternalMessageInfo

func (m *PostRequest) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type PostResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Post                 *Post    `protobuf:"bytes,2,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{13}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type UserProfileRequest struct {
	SearchValue          string       `protobuf:"bytes,1,opt,name=search_value,json=searchValue,proto3" json:"search_value,omitempty"`
	SearchField          Field        `protobuf:"varint,2,opt,name=search_field,json=searchField,proto3,enum=Field" json:"search_field,omitempty"`
	Profile              *UserProfile `protobuf:"bytes,3,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserProfileRequest) Reset()         { *m = UserProfileRequest{} }
func (m *UserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UserProfileRequest) ProtoMessage()    {}
func (*UserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{14}
}

func (m *UserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileRequest.Unmarshal(m, b)
}
func (m *UserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileRequest.Marshal(b, m, deterministic)
}
func (m *UserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileRequest.Merge(m, src)
}
func (m *UserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UserProfileRequest.Size(m)
}
func (m *UserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileRequest proto.InternalMessageInfo

func (m *UserProfileRequest) GetSearchValue() string {
	if m != nil {
		return m.SearchValue
	}
	return ""
}

func (m *UserProfileRequest) GetSearchField() Field {
	if m != nil {
		return m.SearchField
	}
	return Field_ID
}

func (m *UserProfileRequest) GetProfile() *UserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type UserProfileResponse struct {
	Success              bool         `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Profile              *UserProfile `protobuf:"bytes,2,opt,name=profile,proto3" json:"profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UserProfileResponse) Reset()         { *m = UserProfileResponse{} }
func (m *UserProfileResponse) String() string { return proto.CompactTextString(m) }
func (*UserProfileResponse) ProtoMessage()    {}
func (*UserProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{15}
}

func (m *UserProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfileResponse.Unmarshal(m, b)
}
func (m *UserProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfileResponse.Marshal(b, m, deterministic)
}
func (m *UserProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfileResponse.Merge(m, src)
}
func (m *UserProfileResponse) XXX_Size() int {
	return xxx_messageInfo_UserProfileResponse.Size(m)
}
func (m *UserProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfileResponse proto.InternalMessageInfo

func (m *UserProfileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UserProfileResponse) GetProfile() *UserProfile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type FeedRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedRequest) Reset()         { *m = FeedRequest{} }
func (m *FeedRequest) String() string { return proto.CompactTextString(m) }
func (*FeedRequest) ProtoMessage()    {}
func (*FeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{16}
}

func (m *FeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedRequest.Unmarshal(m, b)
}
func (m *FeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedRequest.Marshal(b, m, deterministic)
}
func (m *FeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedRequest.Merge(m, src)
}
func (m *FeedRequest) XXX_Size() int {
	return xxx_messageInfo_FeedRequest.Size(m)
}
func (m *FeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeedRequest proto.InternalMessageInfo

func (m *FeedRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type FeedResponse struct {
	UserFeeds            []*Feed  `protobuf:"bytes,1,rep,name=user_feeds,json=userFeeds,proto3" json:"user_feeds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FeedResponse) Reset()         { *m = FeedResponse{} }
func (m *FeedResponse) String() string { return proto.CompactTextString(m) }
func (*FeedResponse) ProtoMessage()    {}
func (*FeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_69f0e71e027708c3, []int{17}
}

func (m *FeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeedResponse.Unmarshal(m, b)
}
func (m *FeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeedResponse.Marshal(b, m, deterministic)
}
func (m *FeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedResponse.Merge(m, src)
}
func (m *FeedResponse) XXX_Size() int {
	return xxx_messageInfo_FeedResponse.Size(m)
}
func (m *FeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedResponse proto.InternalMessageInfo

func (m *FeedResponse) GetUserFeeds() []*Feed {
	if m != nil {
		return m.UserFeeds
	}
	return nil
}

func init() {
	proto.RegisterEnum("Language", Language_name, Language_value)
	proto.RegisterEnum("Role", Role_name, Role_value)
	proto.RegisterEnum("ParentType", ParentType_name, ParentType_value)
	proto.RegisterEnum("Field", Field_name, Field_value)
	proto.RegisterEnum("Category", Category_name, Category_value)
	proto.RegisterEnum("Post_Type", Post_Type_name, Post_Type_value)
	proto.RegisterEnum("UserProfile_Gender", UserProfile_Gender_name, UserProfile_Gender_value)
	proto.RegisterType((*Feed)(nil), "Feed")
	proto.RegisterType((*UserCategory)(nil), "UserCategory")
	proto.RegisterType((*Post)(nil), "Post")
	proto.RegisterMapType((map[string]string)(nil), "Post.LabelsEntry")
	proto.RegisterMapType((map[string]string)(nil), "Post.ResourceUrlsEntry")
	proto.RegisterType((*Like)(nil), "Like")
	proto.RegisterType((*Comment)(nil), "Comment")
	proto.RegisterType((*UserProfile)(nil), "UserProfile")
	proto.RegisterMapType((map[string]string)(nil), "UserProfile.LabelsEntry")
	proto.RegisterType((*GetAllPostRequest)(nil), "GetAllPostRequest")
	proto.RegisterType((*GetAllPostResponse)(nil), "GetAllPostResponse")
	proto.RegisterType((*CommentRequest)(nil), "CommentRequest")
	proto.RegisterType((*CommentResponse)(nil), "CommentResponse")
	proto.RegisterType((*LikeRequest)(nil), "LikeRequest")
	proto.RegisterType((*LikeResponse)(nil), "LikeResponse")
	proto.RegisterType((*PostRequest)(nil), "PostRequest")
	proto.RegisterType((*PostResponse)(nil), "PostResponse")
	proto.RegisterType((*UserProfileRequest)(nil), "UserProfileRequest")
	proto.RegisterType((*UserProfileResponse)(nil), "UserProfileResponse")
	proto.RegisterType((*FeedRequest)(nil), "FeedRequest")
	proto.RegisterType((*FeedResponse)(nil), "FeedResponse")
}

func init() { proto.RegisterFile("hp.proto", fileDescriptor_69f0e71e027708c3) }

var fileDescriptor_69f0e71e027708c3 = []byte{
	// 1399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xdb, 0x6e, 0xdb, 0x46,
	0x13, 0x16, 0x25, 0x51, 0x26, 0x87, 0xb2, 0x42, 0xaf, 0xf3, 0x27, 0x8c, 0x82, 0xe0, 0x77, 0xd8,
	0xc4, 0x95, 0xdd, 0x80, 0x08, 0xd4, 0x04, 0x6d, 0x83, 0x16, 0x05, 0x2b, 0xd3, 0x36, 0x51, 0x59,
	0x12, 0x56, 0x74, 0xd2, 0x5c, 0x11, 0xb4, 0xb8, 0x76, 0x88, 0x50, 0xa2, 0xca, 0xa5, 0x52, 0xe8,
	0x0d, 0x8a, 0xde, 0xf4, 0x0d, 0x7a, 0xd7, 0xe7, 0xea, 0xab, 0x14, 0xbb, 0x4b, 0x2a, 0x94, 0x9d,
	0x83, 0x8d, 0xde, 0x71, 0xbe, 0x99, 0x9d, 0x99, 0x9d, 0xe3, 0x12, 0x94, 0x37, 0x73, 0x6b, 0x9e,
	0x26, 0x59, 0x62, 0xfe, 0x2d, 0x41, 0xfd, 0x90, 0x90, 0x10, 0xdd, 0x06, 0x39, 0x8e, 0xde, 0x12,
	0x6a, 0x48, 0x3b, 0xb5, 0x8e, 0x8a, 0x05, 0x81, 0x1e, 0x81, 0x32, 0x49, 0xa6, 0x53, 0x32, 0xcb,
	0xa8, 0x51, 0xdd, 0xa9, 0x75, 0xb4, 0xae, 0x62, 0xf5, 0x04, 0x80, 0x57, 0x1c, 0xf4, 0x7f, 0xd0,
	0xb2, 0x24, 0x0b, 0x62, 0x5f, 0x68, 0xa8, 0xed, 0x48, 0x9d, 0x1a, 0x06, 0x0e, 0xf5, 0xb9, 0x9a,
	0xc7, 0xd0, 0x12, 0x02, 0x2b, 0x65, 0x75, 0x2e, 0xb3, 0xc9, 0xd1, 0x5e, 0xa1, 0xe7, 0x1e, 0xd4,
	0xe7, 0x09, 0xcd, 0x0c, 0x79, 0x47, 0xea, 0x68, 0x5d, 0xd9, 0x1a, 0x25, 0x34, 0xc3, 0x1c, 0x32,
	0x31, 0x34, 0x4f, 0x29, 0x49, 0x7b, 0x41, 0x46, 0x2e, 0x92, 0x74, 0x89, 0xee, 0xc2, 0xc6, 0x82,
	0x92, 0xd4, 0x8f, 0x42, 0x43, 0xda, 0x91, 0x3a, 0x2a, 0x6e, 0x30, 0xd2, 0x0d, 0xd1, 0x1e, 0xc0,
	0x44, 0x08, 0x45, 0xdc, 0x95, 0x5a, 0xa7, 0xd5, 0x55, 0xad, 0xe2, 0x1c, 0x2e, 0x31, 0xcd, 0x7f,
	0x6a, 0x50, 0x67, 0x26, 0x50, 0x0b, 0xaa, 0x2b, 0x3d, 0xd5, 0x28, 0x44, 0x0f, 0x00, 0x16, 0xf3,
	0x30, 0xc8, 0x48, 0xe8, 0x07, 0x99, 0x51, 0xe5, 0xae, 0xaa, 0x39, 0x62, 0x67, 0xe8, 0x4b, 0x50,
	0x99, 0x4f, 0x7e, 0xb6, 0x9c, 0x13, 0x7e, 0xd9, 0x56, 0x17, 0xb8, 0xaf, 0x96, 0xb7, 0x9c, 0x13,
	0xac, 0x30, 0x26, 0xfb, 0x42, 0x8f, 0x41, 0xc9, 0xcd, 0x2d, 0xf9, 0x85, 0xd7, 0x3c, 0x59, 0xb1,
	0x98, 0xb9, 0x49, 0x4a, 0x82, 0x2c, 0xe1, 0xd7, 0x91, 0xb9, 0x1b, 0x6a, 0x8e, 0xb8, 0x21, 0x32,
	0x60, 0xe3, 0x0d, 0x09, 0xc2, 0x68, 0x76, 0x61, 0x34, 0x38, 0xaf, 0x20, 0x11, 0x82, 0xfa, 0x59,
	0x12, 0x2e, 0x8d, 0x0d, 0x0e, 0xf3, 0x6f, 0xf4, 0x3d, 0x6c, 0xa6, 0x84, 0x26, 0x8b, 0x74, 0x42,
	0xfc, 0x45, 0x1a, 0x53, 0x43, 0xe1, 0x69, 0xbb, 0x2b, 0x1c, 0xc4, 0x39, 0xeb, 0x34, 0x8d, 0xa9,
	0x33, 0xcb, 0xd2, 0x25, 0x6e, 0xa6, 0x25, 0x08, 0xed, 0x41, 0x23, 0x0e, 0xce, 0x48, 0x4c, 0x0d,
	0x95, 0x1f, 0xdb, 0x12, 0xc7, 0xfa, 0x1c, 0x13, 0x07, 0x72, 0x81, 0xf6, 0x8f, 0xb0, 0x75, 0x45,
	0x1b, 0xd2, 0xa1, 0xf6, 0x96, 0x2c, 0xf3, 0x50, 0xb2, 0x4f, 0x56, 0x57, 0xef, 0x82, 0x78, 0x41,
	0x78, 0x18, 0x55, 0x2c, 0x88, 0x17, 0xd5, 0x6f, 0xa5, 0xf6, 0x77, 0xa0, 0x95, 0xf4, 0xde, 0xe4,
	0xa8, 0xb9, 0x0b, 0x75, 0x1e, 0x60, 0x05, 0xea, 0x9e, 0xf3, 0x8b, 0xa7, 0x57, 0x90, 0x0a, 0xb2,
	0x7b, 0x62, 0x1f, 0x39, 0xba, 0xc4, 0x3e, 0x5f, 0xba, 0x07, 0xce, 0x50, 0xaf, 0x9a, 0x18, 0xea,
	0xac, 0x00, 0xaf, 0x24, 0xf8, 0x3e, 0xa8, 0xf3, 0x20, 0x25, 0xb3, 0x8c, 0x05, 0x5c, 0x68, 0x57,
	0x04, 0xe0, 0x86, 0x97, 0xd2, 0x51, 0xbb, 0x94, 0x0e, 0xf3, 0x77, 0x09, 0x36, 0xf2, 0x8a, 0xbd,
	0x69, 0xe1, 0x7c, 0x5a, 0xf3, 0xba, 0x57, 0xf5, 0x4b, 0x5e, 0x15, 0xb9, 0x96, 0xdf, 0xe7, 0xda,
	0xfc, 0x4b, 0x06, 0x8d, 0x75, 0xc5, 0x28, 0x4d, 0xce, 0xa3, 0xf8, 0x83, 0xd7, 0x8c, 0xa8, 0x1f,
	0x4c, 0xb2, 0xe8, 0x9d, 0x08, 0xa2, 0x82, 0x95, 0x88, 0xda, 0x9c, 0x46, 0x0f, 0xa1, 0x19, 0x51,
	0xd6, 0x90, 0xf3, 0x98, 0x64, 0x44, 0xb8, 0xa3, 0x60, 0x2d, 0xa2, 0xbd, 0x02, 0x62, 0x7d, 0xcd,
	0xbd, 0x23, 0x7e, 0x16, 0x4d, 0x49, 0xde, 0xb3, 0xe2, 0x0a, 0xc4, 0x8b, 0xa6, 0x84, 0x09, 0x88,
	0xdb, 0x09, 0x01, 0x59, 0x08, 0x08, 0x88, 0x0b, 0x3c, 0x00, 0x38, 0x8f, 0x52, 0x9a, 0xf9, 0xb3,
	0x60, 0x4a, 0xf2, 0xf2, 0x55, 0x39, 0x32, 0x08, 0xa6, 0x84, 0x39, 0x18, 0x07, 0x05, 0x57, 0x54,
	0xb1, 0xc2, 0x00, 0xce, 0xfc, 0x0a, 0x1a, 0x17, 0x64, 0x16, 0x92, 0xd4, 0x50, 0x78, 0xef, 0x6c,
	0x5b, 0xa5, 0xbb, 0x5a, 0x47, 0x9c, 0x85, 0x73, 0x11, 0xd6, 0x6a, 0x71, 0x30, 0xbb, 0x58, 0x04,
	0x17, 0xc4, 0x50, 0xf3, 0x56, 0xeb, 0xe7, 0x00, 0x5e, 0xb1, 0xd0, 0x1d, 0x68, 0x4c, 0x93, 0xb3,
	0x28, 0x26, 0x06, 0x88, 0xa9, 0x21, 0x28, 0x56, 0x6a, 0x64, 0x1a, 0x44, 0xb1, 0xa1, 0x89, 0x52,
	0xe3, 0x04, 0x6a, 0x83, 0xc2, 0xa6, 0x0a, 0xf7, 0xae, 0x29, 0xbc, 0x2b, 0x68, 0xc6, 0x9b, 0x07,
	0x94, 0xfe, 0x96, 0xa4, 0xa1, 0xb1, 0x59, 0xe4, 0x4a, 0xd0, 0xac, 0x63, 0x83, 0x30, 0x4c, 0x09,
	0xa5, 0x46, 0x4b, 0x74, 0x6c, 0x4e, 0xb2, 0x09, 0x97, 0x26, 0x31, 0x31, 0x6e, 0x71, 0x17, 0x65,
	0x0b, 0x27, 0x31, 0xc1, 0x1c, 0x42, 0x16, 0x6c, 0x87, 0x11, 0x9d, 0xc7, 0xc1, 0xd2, 0x9f, 0x47,
	0x93, 0x6c, 0x91, 0xf2, 0xfe, 0x35, 0x74, 0xae, 0x60, 0x2b, 0x67, 0x8d, 0x04, 0xe7, 0x34, 0x8d,
	0xd1, 0xd3, 0x55, 0xab, 0x6e, 0xf1, 0x56, 0x35, 0xd6, 0xc2, 0xf3, 0xa1, 0x8e, 0xfd, 0x0f, 0x0d,
	0xf7, 0x1c, 0x1a, 0x22, 0xe0, 0xac, 0xe5, 0x4e, 0xec, 0xbe, 0xa3, 0x57, 0x10, 0x40, 0xe3, 0xd0,
	0xe1, 0xdf, 0x12, 0xfa, 0x1f, 0x6c, 0x8d, 0xb0, 0x73, 0xe8, 0x60, 0x7f, 0x30, 0xf4, 0x7c, 0x6f,
	0xe8, 0x8f, 0xed, 0xd7, 0x7a, 0xcd, 0x7c, 0x02, 0x5b, 0x47, 0x24, 0xb3, 0xe3, 0x98, 0x4f, 0x72,
	0xf2, 0xeb, 0x82, 0xd0, 0xec, 0xa3, 0xa3, 0xdb, 0xfc, 0x19, 0x50, 0x59, 0x9a, 0xce, 0x93, 0x19,
	0x25, 0x2c, 0x98, 0x53, 0x42, 0x29, 0x4b, 0xac, 0x10, 0x2f, 0x48, 0x74, 0x1f, 0x64, 0x36, 0x6a,
	0x8b, 0xcd, 0x94, 0xef, 0x0b, 0x81, 0x99, 0xcf, 0xa0, 0x55, 0x2c, 0xaa, 0xdc, 0xae, 0x09, 0x1b,
	0xf9, 0xfa, 0xe1, 0x8a, 0xca, 0xab, 0xac, 0x60, 0x98, 0x43, 0xb8, 0xb5, 0x3a, 0xf5, 0xde, 0x3e,
	0x5d, 0x4c, 0x26, 0x2c, 0x99, 0x12, 0x6f, 0x91, 0x82, 0x2c, 0x2b, 0xac, 0x7e, 0x4c, 0x61, 0x07,
	0x34, 0x36, 0x81, 0x0a, 0x1f, 0xee, 0x41, 0x9d, 0xed, 0xc8, 0xdc, 0x01, 0xd9, 0xe2, 0x3c, 0x0e,
	0x99, 0x3d, 0x68, 0x0a, 0xc9, 0xcf, 0xda, 0x2d, 0x94, 0x54, 0xaf, 0x2a, 0xe9, 0x80, 0x56, 0x0e,
	0x75, 0xb1, 0x50, 0xa5, 0xab, 0x0b, 0xb5, 0x07, 0xcd, 0xcb, 0x61, 0xfe, 0xb8, 0x39, 0xae, 0xa4,
	0x7a, 0x55, 0xc9, 0x1f, 0x12, 0xa0, 0x52, 0xd5, 0x15, 0x66, 0x1f, 0x42, 0x93, 0x92, 0x20, 0x9d,
	0xbc, 0xf1, 0x45, 0x39, 0x89, 0xbc, 0x69, 0x02, 0x7b, 0xc9, 0x20, 0xb4, 0xb7, 0x12, 0x39, 0x8f,
	0x48, 0x2c, 0x86, 0x70, 0xab, 0xdb, 0xb0, 0x0e, 0x19, 0x55, 0x88, 0x72, 0x02, 0xed, 0xc2, 0xc6,
	0x5c, 0xe8, 0xe7, 0x33, 0x4a, 0xeb, 0x36, 0xcb, 0x95, 0x8e, 0x0b, 0xa6, 0xf9, 0x0a, 0xb6, 0xd7,
	0x7c, 0xf9, 0xec, 0xc5, 0x4a, 0x8a, 0xab, 0x9f, 0x52, 0xbc, 0x0b, 0x1a, 0x7b, 0x22, 0x7d, 0xb6,
	0x7e, 0x9f, 0x41, 0x53, 0xc8, 0xe5, 0x96, 0x1f, 0x01, 0x70, 0xc1, 0x73, 0x42, 0x42, 0xf1, 0xae,
	0x62, 0xe1, 0xe3, 0x22, 0x2a, 0x63, 0xb0, 0x2f, 0xba, 0xff, 0x14, 0x94, 0x62, 0x50, 0xb1, 0xd5,
	0x75, 0xec, 0x0e, 0x0e, 0x5c, 0xbd, 0x82, 0x34, 0xd8, 0x70, 0x06, 0x47, 0x7d, 0x77, 0x7c, 0xac,
	0x4b, 0xa8, 0x09, 0xca, 0x91, 0x8d, 0x8f, 0x5f, 0xd9, 0x7d, 0x57, 0xaf, 0xee, 0xff, 0x00, 0x75,
	0x36, 0x37, 0x50, 0x0b, 0xc0, 0x3e, 0x38, 0x71, 0x07, 0x3e, 0x1e, 0xf2, 0x86, 0xbc, 0x03, 0x68,
	0x34, 0x1c, 0x7b, 0xbe, 0x3d, 0x1a, 0xe1, 0xe1, 0x4b, 0xbb, 0x2f, 0x70, 0x09, 0x6d, 0x82, 0x7a,
	0x3a, 0x76, 0xb0, 0x20, 0xab, 0xfb, 0x5f, 0x00, 0x8c, 0xf8, 0x56, 0x29, 0x56, 0x28, 0x3b, 0x24,
	0x2c, 0xf6, 0x86, 0x27, 0x27, 0xce, 0xc0, 0xd3, 0xa5, 0xfd, 0x5d, 0x90, 0x45, 0xf4, 0x1b, 0x50,
	0x75, 0x0f, 0x44, 0xb7, 0x9f, 0x0c, 0x7f, 0x72, 0xfb, 0xf9, 0x86, 0x75, 0x4e, 0x6c, 0xb7, 0xaf,
	0x57, 0xf7, 0x29, 0x28, 0xab, 0x37, 0x19, 0x40, 0x63, 0x3c, 0x1a, 0x62, 0x6f, 0xac, 0x57, 0x98,
	0xda, 0x81, 0xf3, 0x6a, 0x2c, 0xac, 0xf7, 0xdd, 0x43, 0x67, 0xec, 0xbd, 0x66, 0xd6, 0x91, 0x0e,
	0x4d, 0x77, 0x70, 0x38, 0xf4, 0x6c, 0x77, 0xc0, 0x4d, 0xd5, 0xd0, 0x16, 0x6c, 0x3a, 0x03, 0xcf,
	0xc1, 0x2b, 0xa8, 0xce, 0x6e, 0xe6, 0x39, 0xbd, 0xe3, 0xc1, 0xb0, 0x3f, 0x3c, 0x7a, 0xad, 0xcb,
	0x4c, 0xc7, 0x78, 0xe4, 0x62, 0xd7, 0x3b, 0xb5, 0xfb, 0x7a, 0xa3, 0xfb, 0xa7, 0x0c, 0x35, 0x7b,
	0xe4, 0xa2, 0x17, 0xeb, 0xeb, 0x6f, 0x6d, 0x41, 0xe4, 0xd9, 0x6a, 0xdf, 0xb6, 0x3e, 0x50, 0x14,
	0x66, 0x05, 0xed, 0x81, 0xc2, 0x86, 0x0d, 0x7f, 0xff, 0x35, 0xad, 0x52, 0xd3, 0xb4, 0x37, 0xad,
	0x72, 0x63, 0x98, 0x15, 0xf4, 0x04, 0xb4, 0x1e, 0xdf, 0x79, 0xd7, 0x95, 0x3e, 0x20, 0x6c, 0x7f,
	0x5e, 0x57, 0xfa, 0x94, 0xaf, 0xcb, 0x6b, 0x49, 0x7f, 0x03, 0xf0, 0x7e, 0x42, 0x22, 0x64, 0x5d,
	0x19, 0xae, 0xed, 0x6d, 0xeb, 0xea, 0x08, 0x35, 0x2b, 0xa8, 0x0b, 0x1a, 0xc3, 0x8b, 0x77, 0xcb,
	0x2d, 0x6b, 0x7d, 0x36, 0xb6, 0x75, 0xeb, 0xd2, 0xd8, 0x33, 0x2b, 0xe8, 0x39, 0xb4, 0xf2, 0x6b,
	0xdf, 0xf4, 0x58, 0x7e, 0xff, 0x9b, 0x1e, 0xcb, 0x03, 0x71, 0xa3, 0x63, 0x79, 0x1a, 0xf9, 0x2b,
	0xaf, 0x69, 0x95, 0x46, 0x6d, 0x7b, 0xd3, 0x2a, 0x8f, 0xd3, 0xb5, 0x34, 0x5e, 0x53, 0x3a, 0xbf,
	0xc6, 0x35, 0xa4, 0xcf, 0x1a, 0xfc, 0x6f, 0xea, 0xeb, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x56,
	0x2e, 0x9f, 0x0d, 0x59, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	// used to perform CRUD on UserProfile
	UserProfile(ctx context.Context, in *UserProfileRequest, opts ...grpc.CallOption) (*UserProfileResponse, error)
	// used to perform CRUD on Post
	GetAPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	CreateAPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	DeleteAPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	UpdateAPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	GetAllPost(ctx context.Context, in *GetAllPostRequest, opts ...grpc.CallOption) (*GetAllPostResponse, error)
	// used to perform CRUD on Comment
	GetAComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error)
	CreateAComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error)
	DeleteAComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error)
	UpdateAComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error)
	// used to perform CRUD on Like
	GetALike(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error)
	CreateALike(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error)
	DeleteALike(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) UserProfile(ctx context.Context, in *UserProfileRequest, opts ...grpc.CallOption) (*UserProfileResponse, error) {
	out := new(UserProfileResponse)
	err := c.cc.Invoke(ctx, "/API/UserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetAPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/API/GetAPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateAPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/API/CreateAPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteAPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/API/DeleteAPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateAPost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/API/UpdateAPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetAllPost(ctx context.Context, in *GetAllPostRequest, opts ...grpc.CallOption) (*GetAllPostResponse, error) {
	out := new(GetAllPostResponse)
	err := c.cc.Invoke(ctx, "/API/GetAllPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetAComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error) {
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, "/API/GetAComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateAComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error) {
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, "/API/CreateAComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteAComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error) {
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, "/API/DeleteAComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateAComment(ctx context.Context, in *CommentRequest, opts ...grpc.CallOption) (*CommentResponse, error) {
	out := new(CommentResponse)
	err := c.cc.Invoke(ctx, "/API/UpdateAComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetALike(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error) {
	out := new(LikeResponse)
	err := c.cc.Invoke(ctx, "/API/GetALike", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateALike(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error) {
	out := new(LikeResponse)
	err := c.cc.Invoke(ctx, "/API/CreateALike", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteALike(ctx context.Context, in *LikeRequest, opts ...grpc.CallOption) (*LikeResponse, error) {
	out := new(LikeResponse)
	err := c.cc.Invoke(ctx, "/API/DeleteALike", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	// used to perform CRUD on UserProfile
	UserProfile(context.Context, *UserProfileRequest) (*UserProfileResponse, error)
	// used to perform CRUD on Post
	GetAPost(context.Context, *PostRequest) (*PostResponse, error)
	CreateAPost(context.Context, *PostRequest) (*PostResponse, error)
	DeleteAPost(context.Context, *PostRequest) (*PostResponse, error)
	UpdateAPost(context.Context, *PostRequest) (*PostResponse, error)
	GetAllPost(context.Context, *GetAllPostRequest) (*GetAllPostResponse, error)
	// used to perform CRUD on Comment
	GetAComment(context.Context, *CommentRequest) (*CommentResponse, error)
	CreateAComment(context.Context, *CommentRequest) (*CommentResponse, error)
	DeleteAComment(context.Context, *CommentRequest) (*CommentResponse, error)
	UpdateAComment(context.Context, *CommentRequest) (*CommentResponse, error)
	// used to perform CRUD on Like
	GetALike(context.Context, *LikeRequest) (*LikeResponse, error)
	CreateALike(context.Context, *LikeRequest) (*LikeResponse, error)
	DeleteALike(context.Context, *LikeRequest) (*LikeResponse, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) UserProfile(ctx context.Context, req *UserProfileRequest) (*UserProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserProfile not implemented")
}
func (*UnimplementedAPIServer) GetAPost(ctx context.Context, req *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAPost not implemented")
}
func (*UnimplementedAPIServer) CreateAPost(ctx context.Context, req *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAPost not implemented")
}
func (*UnimplementedAPIServer) DeleteAPost(ctx context.Context, req *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAPost not implemented")
}
func (*UnimplementedAPIServer) UpdateAPost(ctx context.Context, req *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAPost not implemented")
}
func (*UnimplementedAPIServer) GetAllPost(ctx context.Context, req *GetAllPostRequest) (*GetAllPostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPost not implemented")
}
func (*UnimplementedAPIServer) GetAComment(ctx context.Context, req *CommentRequest) (*CommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAComment not implemented")
}
func (*UnimplementedAPIServer) CreateAComment(ctx context.Context, req *CommentRequest) (*CommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAComment not implemented")
}
func (*UnimplementedAPIServer) DeleteAComment(ctx context.Context, req *CommentRequest) (*CommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAComment not implemented")
}
func (*UnimplementedAPIServer) UpdateAComment(ctx context.Context, req *CommentRequest) (*CommentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAComment not implemented")
}
func (*UnimplementedAPIServer) GetALike(ctx context.Context, req *LikeRequest) (*LikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetALike not implemented")
}
func (*UnimplementedAPIServer) CreateALike(ctx context.Context, req *LikeRequest) (*LikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateALike not implemented")
}
func (*UnimplementedAPIServer) DeleteALike(ctx context.Context, req *LikeRequest) (*LikeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteALike not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_UserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/UserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UserProfile(ctx, req.(*UserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetAPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetAPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/GetAPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetAPost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateAPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateAPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/CreateAPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateAPost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteAPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteAPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/DeleteAPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteAPost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateAPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateAPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/UpdateAPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateAPost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetAllPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetAllPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/GetAllPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetAllPost(ctx, req.(*GetAllPostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetAComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetAComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/GetAComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetAComment(ctx, req.(*CommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateAComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateAComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/CreateAComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateAComment(ctx, req.(*CommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteAComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteAComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/DeleteAComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteAComment(ctx, req.(*CommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateAComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateAComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/UpdateAComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateAComment(ctx, req.(*CommentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetALike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetALike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/GetALike",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetALike(ctx, req.(*LikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateALike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateALike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/CreateALike",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateALike(ctx, req.(*LikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteALike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LikeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteALike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/API/DeleteALike",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteALike(ctx, req.(*LikeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserProfile",
			Handler:    _API_UserProfile_Handler,
		},
		{
			MethodName: "GetAPost",
			Handler:    _API_GetAPost_Handler,
		},
		{
			MethodName: "CreateAPost",
			Handler:    _API_CreateAPost_Handler,
		},
		{
			MethodName: "DeleteAPost",
			Handler:    _API_DeleteAPost_Handler,
		},
		{
			MethodName: "UpdateAPost",
			Handler:    _API_UpdateAPost_Handler,
		},
		{
			MethodName: "GetAllPost",
			Handler:    _API_GetAllPost_Handler,
		},
		{
			MethodName: "GetAComment",
			Handler:    _API_GetAComment_Handler,
		},
		{
			MethodName: "CreateAComment",
			Handler:    _API_CreateAComment_Handler,
		},
		{
			MethodName: "DeleteAComment",
			Handler:    _API_DeleteAComment_Handler,
		},
		{
			MethodName: "UpdateAComment",
			Handler:    _API_UpdateAComment_Handler,
		},
		{
			MethodName: "GetALike",
			Handler:    _API_GetALike_Handler,
		},
		{
			MethodName: "CreateALike",
			Handler:    _API_CreateALike_Handler,
		},
		{
			MethodName: "DeleteALike",
			Handler:    _API_DeleteALike_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hp.proto",
}
